### ISSUE TITLE
Closing the drex buffer breaks drex drawer

### ISSUE THREAD

**Issue by SergeyPoznyakAkvelon** [TheBlob42/drex.nvim#28]
Steps to reproduce:

1. Open any file
2. :DrexDrawerToggle
3. Switch back to file (ctrl-w l)
4. Close window :q
5. Now drex drawer is open on the only window
6. Close buffer :bd
7. :DrexDrawerToggle

![image](https://user-images.githubusercontent.com/54810387/188634191-631d8d89-15c7-4cdd-8493-aa732e4bcc58.png)
(The error says "Cannot close the previous window")

I'm using 10d6365

**Comment by TheBlob42** [comment]
After your steps you are still in the "drex drawer window". When you toggle this via `:DrexDrawerToggle` it tries to close it. Since it is the last open editor window the error message you see is being thrown.

The question in this situation is: What would you expect to happen? 
Closing Neovim (since it is the last window)? Open a "new" drawer window? What if you skip step 6?

I would like to keep the implementation as simple as possible for the drawer :slightly_smiling_face:

**Comment by SergeyPoznyakAkvelon** [comment]
> The question in this situation is: What would you expect to happen?
> Closing Neovim (since it is the last window)? Open a "new" drawer window? What if you skip step 6?

I would expect it to open a new drawer window, because there is no indecation that the current window is actually a drex drawer window.

**Comment by SergeyPoznyakAkvelon** [comment]
Good question, not sure. But I think it's no longer a drawer if it's the only window, so maybe just open another window?

**Comment by TheBlob42** [comment]
I thought about a "general" solution, but have to admit that I did not find one that is simple and robust. For now I just catch this special case so that we do not attempt to close the drawer if it is the last window open and log a warning about that case.
